version: '3.8'

services:
  mysqlteste:
    image: mysql:8.0
    container_name: sistemproduct_mysql
    restart: always
    env_file: .env
    ports:
      - "3308:3306"   # Conecta no Workbench via localhost:3308
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sistemproduct_web
    restart: always
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      mysqlteste:      # 👈 agora depende do mysqlteste
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data:
